name: Release

on:
  push:
    branches:
      - main

###########################################################################################
#                                    BUMP VERSION                                         #
###########################################################################################

jobs:
  bump-version:
    name: 'Bump Version on branch master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'cat package.json'
        run: cat ./lib/flagsmith/package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PACKAGEJSON_DIR: 'lib/flagsmith/package.json'

      - name: 'cat package.json'
        run: cat ./lib/flagsmith/package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"


###########################################################################################
#                                    SEMANTIC RELEASE                                     #
###########################################################################################

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - bump-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: main
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
